### ISSUE TITLE
ads list

### ISSUE THREAD

**Issue by hmakmur** [socram8888/not-on-my-shift#1]
First thanks for making the host files for malware list.

In the host file in https://orca.pet/notonmyshift/,  i notice that you have ads there. I am not sure if this ads site is also malware sites or just another ads sites not already included in some other ads block lists.

If the ads list is not a malware sites, could you separate them from the malware 
lists? I am worry about blocking ads sites. In the past when I do that, certain important streaming sites stop working.

**Comment by socram8888** [comment]
Yes, those ads are not available in any other lists I've looked for. These should not affect you for streaming services - they are not used by reputable streaming sites like YouTube, Twitch or the like.

The only sites on the block list are illegal ones that use phishing techniques and use hacked websites to show [those shady ads saying you've got a free iPhone](https://consquarters12.live/8463483161/) - so shady this link will expire in about two days so you can't track the domain owner. It will not affect you for visiting YouTube, Twitch or any other reputable streaming site.
