### ISSUE TITLE
Please,review and reevaluate your list(many issues)

### ISSUE THREAD

**Issue by dnmTX** [socram8888/not-on-my-shift#12]
Hi there Marcos @socram8888 . 
As you know your list is...was part of the [StevenBlack's list](https://github.com/StevenBlack/hosts) but after your latest update it was removed,temporary for now until all the issues of concern are resolved. 
To begin with,your latest update added 8.000+ `autodiscover.*` domains. Most of them are dead anyway and lots and lots are invalid. Basically junk,which most of the DNS Resolvers will not able to read and only litter with errors.
Just a small example of the invalid once:
```
0.0.0.0 autodiscover.*.compute-1.amazonaws.com
0.0.0.0 autodiscover.lørenskog.no
0.0.0.0 autodiscover.várggát.no
0.0.0.0 autodiscover.世界
0.0.0.0 autodiscover.भारतम्..........
```
You can follow up on our conversation [HERE](https://github.com/StevenBlack/hosts/commit/c109e935d7714befab6e3ba4fc85e5f408a5416c) and i also opened a separate issue for your list review [HERE](https://github.com/StevenBlack/hosts/issues/1769) so you can let us know about the changes you're plannig to do....or not.
My presonal advise....remove all of the `autodiscover.*` domains and stop listening to unreliable sources where you're literally can not verify the information and stick to what you know. You were doing great...till now(sight).
Thanks and hoping that your list will be back soon 👍

**Comment by socram8888** [comment]
The idea behind adding these domains before they exist is exactly to have them blocked before they supposed to be a threat - playing whack-a-mole with the isn't gonna be fun.

However you are right that many of those 8000 domains are unlikely to ever exist, so I've reduced considerably the list from the previous 8k domains to roughly 800, those that can be freely registered on OVH.

For domains with international characters (Chinese, Japanese, etc...) I've implemented IDNA-encoding so they should be supported on any hosts resolver:
```
0.0.0.0 autodiscover.xn--c1avg
0.0.0.0 autodiscover.xn--pgbs0dh
0.0.0.0 autodiscover.xn--ngbc5azd
0.0.0.0 autodiscover.xn--i1b6b1a6a2e
0.0.0.0 autodiscover.xn--q9jyb4c
0.0.0.0 autodiscover.xn--45q11c
0.0.0.0 autodiscover.xn--nqv7f
0.0.0.0 autodiscover.xn--6frz82g
0.0.0.0 autodiscover.xn--hxt814e
```
