### ISSUE TITLE
Added your list to my project

### ISSUE THREAD

**Issue by lightswitch05** [socram8888/not-on-my-shift#2]
Hello,

I added your list to my blocklist search page. Example search: https://blocklist-tools.developerdan.com/entries/search?q=mciegroup.ru

It looks like some other combination lists might already be including your list, but as time goes by and you add more items to your list, it will become obvious that your list is the source. Anyways, I thought I would let you know it was being included.

**Comment by socram8888** [comment]
Oh hey, thanks for this tool and for letting me know!

**Comment by socram8888** [comment]
For the record, I've linked it from the [resources section](https://orca.pet/notonmyshift/#resources) of the project page, since it is a genuinely useful tool.

**Comment by lightswitch05** [comment]
Neat, I'm glad you think so!
