### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by obeho** [socram8888/not-on-my-shift#3]
Please whitelist `list-manage.com` I'm unable to open links like `thenextweb.us1.list-manage.com` from my newsletter

For more information,

`https://www.quora.com/Why-does-MailChimp-use-multiple-list-manage-com-domains/answer/Amanda-Egan-28?share=1`

So it is understandable why `list-manage.com` altogether is blocked, as some links might've been malicious in some shared domain.

**Comment by socram8888** [comment]
Hello! Sorry for the inconvenience. I've modified the rule to a ABP-only rule that blocks the tracking beacons alone (see https://github.com/socram8888/not-on-my-shift/commit/09f9ddb957ac0e4d1181f02ba60ee30ef9eb5db4#diff-67e6d4f7b474aaf3e5962229e48ea8feb8857acd50a7c9c8f80bb1d87898ff52R960)

Should be published by now already

**Comment by obeho** [comment]
Thank you. I see that `list-manage.com` is removed from the domain list, and is present in AdBlock list. Does this mean if I use the Adblock list in uBlock origin, I will still be able to open any shared domain like `xxxxxx.us3.list-manage.com` but without tracking? (because the beacon is removed)

**Comment by socram8888** [comment]
That is correct.

Most of the beacon blocking are in fact implemented as ABP-only rules, since that exactly allow clicking on links while blocking beacons only.

**Comment by obeho** [comment]
Thank you. Sorry for asking, but are abp rules to be added under 'My rules' in uBlock?

**Comment by socram8888** [comment]
Nope. On uBlock, go to the "Filter lists" tab, and right at the bottom there's a "Personalized" section. Click on "Import", paste in the URL and hit on apply changes.

**Comment by obeho** [comment]
Yup, done. Thanks. I hit apply changes, can you please tell where I can confirm that I added the list?

**Comment by socram8888** [comment]
If you click the tiny eye on the right of filter list, the entire list of rules will popup. You should see around line 895 the three List-manage rules.
