### ISSUE TITLE
SMS Phishing

### ISSUE THREAD

**Issue by N8Z7JMYLU** [socram8888/not-on-my-shift#5]
The following domains are currently being used in the aftermath of the latest Facbook data leak affecting 500M people. They are being sent by SMS. Expecting more domains to follow.

```
https://www.interieurarchitect-maasdam.nl/pkge/?nqitghaqiq19qi
http://ibcp.cz/track/?v18qwei92hj29
http://aiceltravel.com/trck/?rkqutw2oqt2j
http://avericstech.com/pkg/?ghskakkwja9g
http://allfordn.com/pkge/?wu28e78ga9ou
http://productcatalog.cn/track/?rio2j3822iau
```

**Comment by socram8888** [comment]
Thanks. Can you provide a direct link to the phising page that's being sent, please? Ie with the path and stuff.

**Comment by N8Z7JMYLU** [comment]
Updated the links.

**Comment by socram8888** [comment]
Perfect. This is a known organization for which I've even added an automatic domain blocking tool which I manually run every now and then. I'll execute it now.
