### ISSUE TITLE
SMS phishing - Fake message from the French Post

### ISSUE THREAD

**Issue by levaphenyl** [socram8888/not-on-my-shift#6]
The message tells to pay toll fees for a parcel and points to the not-suspicious-at-all URL:
```
http://z0g.me/kekKH
```

I already reported the website but I suggest it here in the mean time :wink:.
Thank you for your great work!

**Comment by socram8888** [comment]
Thanks for the report. Added in c9f395e85ab4a9c86afd257f031b6af48b7bbff4.
