### ISSUE TITLE
Phishing

### ISSUE THREAD

**Issue by iam-py-test** [socram8888/not-on-my-shift#7]
### What domain are you submitting
```
gogle.net
```
#### Why are you submitting this domain?
gogle[.]net is a typo-squatting domain which has been used for malware, phishing, and scams.
Please see https://github.com/DandelionSprout/adfilt/issues/188 for more information.
I am not sure if you still accept domain submissions or what criteria are needed, so please tell me if I need to update this report with more information.
WHOIS status:
```
WHOIS Online: Yes
Registrant Contact Information:
Name: Domain Admin
Organization: Whois protection (this company does not own this domain name)
Address: Not Disclosed
City: Praha 4
Country: CZ
Phone: +420.226517351
Fax: +420.226517341


IP addr: 54.235.212.68 
```
VirusTotal scan: 
![image](https://user-images.githubusercontent.com/84232764/132222908-9008caf5-a833-49e1-a2ca-360f68c5976b.png)

**Comment by socram8888** [comment]
Added in bc27eee59d851b2f55cee395709b420c98018adb. Thanks!

**Comment by iam-py-test** [comment]
@socram8888 thanks for the quick reply!
