### ISSUE TITLE
Website content blocked - wp/*.php

### ISSUE THREAD

**Issue by ArmynC** [socram8888/not-on-my-shift#8]
Hello! `https://vaccinare-covid.gov.ro/platforma-programare/` website map content (pin) is broken probably due to 

> ! Most hacked installations of WordPress use the wp-* folders to stay stealth, so I'll block
> ! unusual usage of these files, which 99.9% should be malware uploads.
> /wp-content/*.php^$all
> /wp-upload/*.php^$all
> /wp-includes/*$document

![Capture](https://user-images.githubusercontent.com/16375271/134143603-bfc79622-8c6a-4e49-a33b-9eaff332ac46.PNG)

- - -

### ON:
![on](https://user-images.githubusercontent.com/16375271/134144156-d1273822-a267-4f3e-a9b6-e9fe6e105711.png)

### OFF:
![off](https://user-images.githubusercontent.com/16375271/134144166-247df54b-904f-43b6-8f97-aa371e78fa3e.png)

**Comment by socram8888** [comment]
Thanks for the report. I've replaced it with a more specific ˋ/wp-content/uploads/ˋ entry.
