### ISSUE TITLE
Issues with AutoDiscovery

### ISSUE THREAD

**Issue by psophos** [socram8888/not-on-my-shift#9]
I was wondering if this would be a goof blocklist to add the following list to: 
https://github.com/guardicore/labs_campaigns/tree/master/Autodiscover

The issue is that email client autodiscovery can fail in such a was as to potentially disclose credentials. 
Should the autodiscovery process connect to any of the listed domains then it has already failed so blocking the domains should not cause any issues. 

More in their write-up here: https://www.guardicore.com/labs/autodiscovering-the-great-leak/

Regards.

**Comment by socram8888** [comment]
Thanks for the tip! Added all of the domains from their list.
